In [8]:
import numpy as np
a = np.arange(6) # if upper and lower limite not defined lower limit is set to 0
a

array([0, 1, 2, 3, 4, 5])

In [12]:
np.arange(12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [15]:
np.arange(24).reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [20]:
print(np.arange(10000)) # numpy auto skip the mid numbers if the array is too large

[   0    1    2 ... 9997 9998 9999]


In [37]:
print(np.arange(10000).reshape(100,100)) #reshaoe arranges the array in the given axes and elements set

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [36]:
import sys
np.set_printoptions(threshold=1000)  # sys module should be imported

In [69]:
a = np.array([10,20,30,40])
b = np.arange(4)
add = a + b # additon/subtraction on array with same index
sub = a - b
mul = a * b
div = a / 2
sqr = b **2
cub = b ** 3

In [59]:
a

array([10, 20, 30, 40])

In [60]:
b

array([0, 1, 2, 3])

In [61]:
add

array([10, 21, 32, 43])

In [62]:
sub

array([10, 19, 28, 37])

In [63]:
mul

array([  0,  20,  60, 120])

In [64]:
div

array([ 5., 10., 15., 20.])

In [70]:
sqr

array([0, 1, 4, 9], dtype=int32)

In [71]:
cub

array([ 0,  1,  8, 27], dtype=int32)

In [77]:
fn = 10 * np.sin(a)
fn

array([-5.44021111,  9.12945251, -9.88031624,  7.4511316 ])

In [81]:
a < 20

array([ True, False, False, False])

In [88]:
A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[3,4]])

In [89]:
A

array([[1, 1],
       [0, 1]])

In [90]:
B

array([[2, 0],
       [3, 4]])

In [91]:
A * B #cartesian product of same array index digits


array([[2, 0],
       [0, 4]])

In [134]:
A @ B #matrix product

array([[5, 4],
       [3, 4]])

In [135]:
A.dot(B) #another matrix product

array([[5, 4],
       [3, 4]])

In [203]:
rg = np.random.default_rng(3) # create instance of default random number generator
rg 

Generator(PCG64) at 0x2C61149E820

In [204]:
a = np.ones((2,3),dtype=int)
b = rg.random((2,3))

In [205]:
b

array([[0.08564917, 0.23681051, 0.80127447],
       [0.58216204, 0.09412864, 0.43312694]])

In [186]:
a

array([[1, 1, 1],
       [1, 1, 1]])

In [199]:
a *= 3 #create a new array instead of updating the old one

In [200]:
a

array([[3, 3, 3],
       [3, 3, 3]])

In [156]:
a += 3

In [171]:
b = np.arange(6).reshape(2,3)

In [206]:
b +=a #b = b+a -- b is 0.961 ... & a is array of 1
a

array([[1, 1, 1],
       [1, 1, 1]])

In [207]:
b

array([[1.08564917, 1.23681051, 1.80127447],
       [1.58216204, 1.09412864, 1.43312694]])

#### When operating with arrays of different types, the type of the resulting array corresponds to the more general or precise one (a behavior known as upcasting).

In [208]:
a1 = np.ones(3, dtype= np.int32)
a1

array([1, 1, 1])

In [210]:
from numpy import pi
a2 = np.linspace(0, pi , 3)
a2

array([0.        , 1.57079633, 3.14159265])

In [211]:
a2.dtype.name

'float64'

In [212]:
a1.dtype.name

'int32'

In [214]:
b

array([[1.08564917, 1.23681051, 1.80127447],
       [1.58216204, 1.09412864, 1.43312694]])

In [220]:
arr = np.array([(1,2,3),(4,5,6)])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [225]:
exp = np.exp(arr * 2)
exp

array([[7.38905610e+00, 5.45981500e+01, 4.03428793e+02],
       [2.98095799e+03, 2.20264658e+04, 1.62754791e+05]])

In [226]:
exp.dtype.name

'float64'

In [227]:
exp1 = np.exp(arr * 1j)
exp1

array([[ 0.54030231+0.84147098j, -0.41614684+0.90929743j,
        -0.9899925 +0.14112001j],
       [-0.65364362-0.7568025j ,  0.28366219-0.95892427j,
         0.96017029-0.2794155j ]])

In [228]:
exp1.dtype.name

'complex128'

In [244]:
rand = rg.random((2,3))
rand

array([[0.21386699, 0.85864193, 0.12675498],
       [0.29675777, 0.49284698, 0.84946041]])

In [246]:
rand.sum()

2.838329061079676

In [247]:
rand.min()

0.1267549797183054

In [248]:
rand.max()

0.8586419321659043

In [250]:
arr = np.array([(1,2,3),(43,42,11)])
arr

array([[ 1,  2,  3],
       [43, 42, 11]])

In [251]:
arr.sum()

102

In [253]:
arr.min()

1

In [254]:
arr.max()

43