In [74]:
import numpy as np
arr = np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
arr.sum(axis = 0) #sum of each column/dimension (12 = 0+4+8)

array([12, 15, 18, 21])

In [7]:
arr.sum(axis = 1) #sum of each row (6 = 0+1+2+3)

array([ 6, 22, 38])

In [8]:
arr.min(axis=0) # 0 - across column

array([0, 1, 2, 3])

In [9]:
arr.min(axis=1) #1- across row

array([0, 4, 8])

In [11]:
arr.max(axis=0)

array([ 8,  9, 10, 11])

In [12]:
arr.max(axis=1)

array([ 3,  7, 11])

In [15]:
arr.cumsum(axis=0) #cummulatuve sum for each element/field (last sum + current field value)

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21]], dtype=int32)

In [14]:
arr.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)

### Universal Functions!

> mathematical functions!

sin, cos, exp etc

In [17]:
arr = np.arange(3)
arr

array([0, 1, 2])

In [18]:
np.exp(arr)

array([1.        , 2.71828183, 7.3890561 ])

In [27]:
arr1 = np.sqrt(arr) #square root
arr1

array([0.        , 1.        , 1.41421356])

In [30]:
arr2 = np.array([1.12,-2.3,3.34343])
arr2

array([ 1.12   , -2.3    ,  3.34343])

In [32]:
arr + arr2

array([ 1.12   , -1.3    ,  5.34343])

In [34]:
np.add(arr, arr1, arr2) # add function

array([0.        , 2.        , 3.41421356])

In [43]:
# statistical functions

np.min(arr)
np.max(arr)
np.median(arr)
np.mean(arr)
np.std(arr)


0.816496580927726

### Indexing, Slicing and Iterating
> One-dimensional arrays can be indexed, sliced and iterated over, much like lists and other Python sequences.

In [64]:
iarr = np.arange(10)**3
iarr

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [52]:
iarr[0] # 0 index is the starting of array
iarr[2]
#iarr[22] # out of bound
iarr[5]
iarr[:6:2] # starting 0 index till 6th index and taking every 2nd element

array([ 0,  8, 64], dtype=int32)

In [53]:
iarr[-1]

729

In [55]:
iarr[:-3] #starting from first till -4 inclusive

array([  0,   1,   8,  27,  64, 125, 216], dtype=int32)

In [57]:
iarr[3:6]

array([ 27,  64, 125], dtype=int32)

In [59]:
iarr[::-1] #whole array with negative slicing, going back in array list

array([729, 512, 343, 216, 125,  64,  27,   8,   1,   0], dtype=int32)

In [65]:
iarr

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [66]:
iarr[:4:2] = 1000 #setting up the every 2nd element in array to 1000
iarr

array([1000,    1, 1000,   27,   64,  125,  216,  343,  512,  729],
      dtype=int32)

In [68]:
iarr[::-1]

array([ 729,  512,  343,  216,  125,   64,   27, 1000,    1, 1000],
      dtype=int32)

In [71]:
iarr

array([1000,    1, 1000,   27,   64,  125,  216,  343,  512,  729],
      dtype=int32)

In [74]:
iarr
for i in iarr:
    print(i**(1/3))
    #print("*" * 10)

9.999999999999998
1.0
9.999999999999998
3.0
3.9999999999999996
5.0
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


> _Multidimensional arrays can have one index per axis. These indices are given in a tuple separated by commas:_

In [3]:
def f(x,y): #define function with variable x,y
    return 10 * x + y
val = np.fromfunction(f, (5,4), dtype=np.int32)
val

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [83]:
np.reshape(val,(4,5))

array([[ 0,  1,  2,  3, 10],
       [11, 12, 13, 20, 21],
       [22, 23, 30, 31, 32],
       [33, 40, 41, 42, 43]])

In [86]:
val[2:3] #in case of array slicing, every axis is considered as an array element

array([[20, 21, 22, 23]])

In [89]:
val[::-1] #reverse of array

array([[40, 41, 42, 43],
       [30, 31, 32, 33],
       [20, 21, 22, 23],
       [10, 11, 12, 13],
       [ 0,  1,  2,  3]])

In [91]:
val[-1:-3:-1]

array([[40, 41, 42, 43],
       [30, 31, 32, 33]])

In [93]:
val

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [95]:
val[2,3] #starting index is always 0 in array, 2nd axis index pos and 3rd index element in that axis

23

In [98]:
val[0:,2] #for all the rows select 3rd element

array([ 2, 12, 22, 32, 42])

In [103]:
val[:,2] #starting and ending index not defined so it will be entire array list

array([ 2, 12, 22, 32, 42])

In [4]:
val[1:3,:]

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [6]:
val

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [7]:
val[-1] #last index of array, consider the entire array run

array([40, 41, 42, 43])

In [13]:
arr = np.arange(5).reshape(5)
arr

array([0, 1, 2, 3, 4])

In [14]:
arr[3], arr[1], arr[2]

(3, 1, 2)

In [16]:
arr[[0,2,-1]]

array([0, 2, 4])

In [17]:
arr

array([0, 1, 2, 3, 4])

In [18]:
arr.dtype

dtype('int32')

In [20]:
f_arr = np.array([1.0,1.5,2.0,2.5])
f_arr

array([1. , 1.5, 2. , 2.5])

In [21]:
f_arr.dtype

dtype('float64')

In [31]:
x = np.array([1.1,2.2,3.3,4.4], dtype=np.int8) # converted the float array to int
x

array([1, 2, 3, 4], dtype=int8)

In [27]:
c = np.array(['a','b','c'])

In [34]:
c.dtype # unicode representation of the string array in numpy

dtype('<U1')

In [32]:
x

array([1, 2, 3, 4], dtype=int8)

In [37]:
A = np.array([[1,2,3],[4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
A.dtype

dtype('int32')

In [40]:
A.shape # 2-dimension, 3-elements in each dim

(2, 3)

In [42]:
A.ndim # no of dimensions

2

In [44]:
A.size #no of total elements dim*elements

6

In [46]:
B = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ]
])

In [47]:
B

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [48]:
B.shape

(2, 2, 3)

In [49]:
B.ndim

3

In [50]:
B.size

12

In [62]:
C = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9]
    ]
],dtype=object)

In [53]:
C.dtype

dtype('O')

In [54]:
C.shape

(2,)

In [55]:
C.ndim

1

In [56]:
C.size

2

In [64]:
A = np.array([
#.   0. 1. 2.
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8, 9]  # 2
])

In [67]:
# A [d1, d2, d3, d4]
A[0][1]

2

In [68]:
A[:,1]

array([2, 5, 8])

In [69]:
A[1:2,1]

array([5])

In [70]:
A[:,:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [72]:
A[1] = np.array([10,20,30]) 

In [73]:
A

array([[ 1,  2,  3],
       [10, 20, 30],
       [ 7,  8,  9]])