In [3]:
import numpy as np
arr = np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
arr.sum(axis = 0) #sum of each column/dimension (12 = 0+4+8)

array([12, 15, 18, 21])

In [7]:
arr.sum(axis = 1) #sum of each row (6 = 0+1+2+3)

array([ 6, 22, 38])

In [8]:
arr.min(axis=0)

array([0, 1, 2, 3])

In [9]:
arr.min(axis=1)

array([0, 4, 8])

In [11]:
arr.max(axis=0)

array([ 8,  9, 10, 11])

In [12]:
arr.max(axis=1)

array([ 3,  7, 11])

In [15]:
arr.cumsum(axis=0) #cummulatuve sum for each element/field (last sum + current field value)

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21]], dtype=int32)

In [14]:
arr.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)