In [1]:
import numpy as np

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Useful NumPy functions

In [47]:
np.random.random(size =20) # random array of 5 +ve elements

array([0.73569289, 0.65194209, 0.77066171, 0.2632086 , 0.70608473,
       0.8656415 , 0.91857794, 0.65418328, 0.77890983, 0.09342839,
       0.66361495, 0.72035126, 0.84630139, 0.20958241, 0.81058211,
       0.40289057, 0.86107971, 0.26612721, 0.77255572, 0.538777  ])

In [48]:
np.random.normal(size = 10)

array([ 1.83776729, -0.92839517, -0.41282835,  0.3127624 ,  0.32231843,
        1.48765421, -0.94007382, -0.03433325,  0.17249996, -1.54256839])

In [15]:
np.random.rand(3)

array([0.64413219, 0.88111388, 0.76473845])

In [17]:
np.random.default_rng(10)

Generator(PCG64) at 0x25D0D5E59E0

In [43]:
np.random.randint(100) #it will generate random integer number

55

In [51]:
np.random.rand(2,3) # an n-dim array with 2 dim and 3 elements each

array([[0.84762225, 0.74486231, 0.86793886],
       [0.30110357, 0.9713596 , 0.83533391]])

***

In [52]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
np.arange(4,10) # an array with start at 4 and end at 10 excluding

array([4, 5, 6, 7, 8, 9])

In [62]:
np.arange(0,10,-1)

array([], dtype=int32)

In [63]:
np.arange(15,10,-1)

array([15, 14, 13, 12, 11])

In [64]:
np.arange(0,5,1)

array([0, 1, 2, 3, 4])

***

In [66]:
np.arange(10).reshape(2,5) #2 dim with 5 elements each

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [68]:
np.arange(10).reshape(5,2) #5 dim with 2 elements each

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [69]:
np.arange(10).all

<function ndarray.all>

In [71]:
np.arange(10).item

<function ndarray.item>

***

In [75]:
np.zeros((3,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [77]:
np.empty(5)

array([2.12199579e-314, 1.28380745e-311, 4.70350495e-321, 6.95165821e-310,
       0.00000000e+000])

In [81]:
np.empty((2,2))

array([[2.12199579e-314, 1.28380745e-311],
       [4.70350495e-321, 6.95165821e-310]])

In [83]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [84]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [86]:
np.identity((5),dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [87]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [93]:
np.eye((6,5),dtype=int) #error

In [97]:
np.eye(8,6, k=2) #k is the index which is set to 1, here K=2 means 3rd index position and tghen diagonaly

array([[0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [99]:
"Hello World"[6] #6th index position in string

'W'