In [21]:
import numpy as np
import math

In [25]:
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()

print(c)
print("Vectorized time version: " + str(1000 * (toc-tic)) + "ms")

c = 0
tic = time.time()
for i in range(1000000):
    c += a[i] * b[i]
toc = time.time()

print(c)
print("Non-vectorized version/ FOr loop: " + str(1000*(toc-tic)) + "ms")

[0.16813431 0.516453   0.76249205 ... 0.14561621 0.14889535 0.10238212]
249872.3594297701
Vectorized time version: 0.9565353393554688ms
249872.35942977323
Non-vectorized version/ FOr loop: 521.1412906646729ms


In [34]:
u = np.random.rand(1000000,1)
v = np.random.rand(1000000,1)
# take exponential function for each element in the array
for i in range(1000000):
    v[i] = math.exp(u[i])

In [35]:
# vectorized computation.. removing explicit for loop
u_vec = np.exp(u)
u_vec

array([[2.04603977],
       [1.3123917 ],
       [1.30755496],
       ...,
       [1.39205769],
       [1.35393701],
       [1.66081548]])

In [39]:
np.log(u)
np.abs(u)
np.sqrt(u)
np.maximum(u,0)

array([[0.7159061 ],
       [0.2718512 ],
       [0.26815895],
       ...,
       [0.330783  ],
       [0.30301665],
       [0.50730874]])

In [41]:
# Broadcasting example:

import numpy as np
A = np.array([[56.0, 0.0, 4.4, 68.0],
             [1.2,104.0,52.0,8.0],
             [1.8,135.0,99.0,0.9]])

print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [42]:
cal = A.sum(axis=0) # sum vertically
print(cal)

[ 59.  239.  155.4  76.9]


In [49]:
percentage = 100 *A/cal # briadcasting we can use reshape command if not sure of dimention os cal
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [59]:
A = np.random.randint(1,10, size =(3,4))
A

array([[1, 1, 3, 6],
       [2, 2, 5, 1],
       [7, 8, 8, 2]])

In [61]:
B = np.array([1,2,3,4])
B

array([1, 2, 3, 4])

In [63]:
A + B # here A is (3,4) matrix and B is (1,4) matrix so Broadcasting by python makes it add in same dimension

array([[ 2,  3,  6, 10],
       [ 3,  4,  8,  5],
       [ 8, 10, 11,  6]])

In [74]:
# tips and tricks to find bug in code..
a = np.random.randn(5)
print(a)
print(a.shape)
print(a.T) # T is transpose of A; but here A is not a row vector or matrix, gives rank 1 array...
print(np.dot(a, a.T)) 

[ 0.04154141  0.33841227  0.69311719 -0.59877165  1.14296967]
(5,)
[ 0.04154141  0.33841227  0.69311719 -0.59877165  1.14296967]
2.2615671576030447


In [73]:
# row vector means the shape of matrix is (1,n)
# column vector means the shape of matrix is (m,1)

A = np.random.randn(5,1) # here A is a row vector
print(A)
print('\n')
print(A.T)
print('\n')
print(np.dot(A, A.T))

[[-0.61400513]
 [ 2.03753371]
 [ 0.63661477]
 [ 0.16950964]
 [ 0.0228478 ]]


[[-0.61400513  2.03753371  0.63661477  0.16950964  0.0228478 ]]


[[ 3.77002305e-01 -1.25105616e+00 -3.90884736e-01 -1.04079790e-01
  -1.40286664e-02]
 [-1.25105616e+00  4.15154361e+00  1.29712405e+00  3.45381608e-01
   4.65531622e-02]
 [-3.90884736e-01  1.29712405e+00  4.05278363e-01  1.07912341e-01
   1.45452468e-02]
 [-1.04079790e-01  3.45381608e-01  1.07912341e-01  2.87335184e-02
   3.87292234e-03]
 [-1.40286664e-02  4.65531622e-02  1.45452468e-02  3.87292234e-03
   5.22021954e-04]]


In [77]:
assert(A.shape == (5,1)) # forcing the column vector to an array
A

array([[-0.61400513],
       [ 2.03753371],
       [ 0.63661477],
       [ 0.16950964],
       [ 0.0228478 ]])

In [80]:
a=np.random.randn(4,3) 
b=np.random.randn(1,3)
c=a*b
c

array([[-7.87764056e-01,  4.33816258e-02,  3.61426778e-01],
       [-4.11161115e-01, -1.86442017e-01, -7.39514110e-04],
       [-2.15445001e-01, -1.47968030e-01,  9.42608036e-01],
       [-2.09991528e-01,  6.06260618e-01, -9.67132741e-02]])

In [85]:
a=np.array([[1,1],[1,-1]])
print(a)
b=np.array([[2],[3]])
print(b)
c = a + b
c

[[ 1  1]
 [ 1 -1]]
[[2]
 [3]]


array([[3, 3],
       [4, 2]])