In [21]:
import numpy as np
import math

In [25]:
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()

print(c)
print("Vectorized time version: " + str(1000 * (toc-tic)) + "ms")

c = 0
tic = time.time()
for i in range(1000000):
    c += a[i] * b[i]
toc = time.time()

print(c)
print("Non-vectorized version/ FOr loop: " + str(1000*(toc-tic)) + "ms")

[0.16813431 0.516453   0.76249205 ... 0.14561621 0.14889535 0.10238212]
249872.3594297701
Vectorized time version: 0.9565353393554688ms
249872.35942977323
Non-vectorized version/ FOr loop: 521.1412906646729ms


In [34]:
u = np.random.rand(1000000,1)
v = np.random.rand(1000000,1)
# take exponential function for each element in the array
for i in range(1000000):
    v[i] = math.exp(u[i])

In [35]:
# vectorized computation.. removing explicit for loop
u_vec = np.exp(u)
u_vec

array([[2.04603977],
       [1.3123917 ],
       [1.30755496],
       ...,
       [1.39205769],
       [1.35393701],
       [1.66081548]])

In [39]:
np.log(u)
np.abs(u)
np.sqrt(u)
np.maximum(u,0)

array([[0.7159061 ],
       [0.2718512 ],
       [0.26815895],
       ...,
       [0.330783  ],
       [0.30301665],
       [0.50730874]])