In [1]:
import numpy as np

In [12]:
rg = np.random.default_rng(1) 
a = np.floor(10 * rg.random((3, 4)))
a

array([[5., 9., 1., 9.],
       [3., 4., 8., 4.],
       [5., 0., 7., 5.]])

In [14]:
a.shape

(3, 4)

In [16]:
a.ravel()

array([5., 9., 1., 9., 3., 4., 8., 4., 5., 0., 7., 5.])

In [18]:
a.reshape(6,2)

array([[5., 9.],
       [1., 9.],
       [3., 4.],
       [8., 4.],
       [5., 0.],
       [7., 5.]])

In [19]:
a.T

array([[5., 3., 5.],
       [9., 4., 0.],
       [1., 8., 7.],
       [9., 4., 5.]])

In [23]:
a.T.shape

(4, 3)

In [25]:
a.T.size

12

In [26]:
a.T.ndim

2

In [27]:
a

array([[5., 9., 1., 9.],
       [3., 4., 8., 4.],
       [5., 0., 7., 5.]])

In [29]:
a.resize((2,6)) #resize changes the structure permanently in an array
a

array([[5., 9., 1., 9., 3., 4.],
       [8., 4., 5., 0., 7., 5.]])

In [30]:
a

array([[5., 9., 1., 9., 3., 4.],
       [8., 4., 5., 0., 7., 5.]])

In [33]:
a.reshape(3,4) #reshape modifies the array as per the argument but does not change the array permanently

array([[5., 9., 1., 9.],
       [3., 4., 8., 4.],
       [5., 0., 7., 5.]])

In [34]:
a

array([[5., 9., 1., 9., 3., 4.],
       [8., 4., 5., 0., 7., 5.]])

In [50]:
a = np.floor(10 * rg.random((2,2)))
a

array([[0., 8.],
       [8., 8.]])

In [51]:
b = np.floor(10 * rg.random((2,2)))
b

array([[4., 2.],
       [0., 6.]])

In [52]:
np.vstack((a,b)) # vertical stacking

array([[0., 8.],
       [8., 8.],
       [4., 2.],
       [0., 6.]])

#### To vstack the arrays, the dimension size must be same.

In [54]:
np.hstack((a,b)) # horizontal stacking

array([[0., 8., 4., 2.],
       [8., 8., 0., 6.]])

In [59]:
a = np.array([1,2,3])

In [60]:
b = np.array([3,4,5])

In [62]:
c = np.array([6,7,8])

In [65]:
np.column_stack((a,b,c)) # stack column wise elements of 1D array into 2D arrays
# returns a 2D array

array([[1, 3, 6],
       [2, 4, 7],
       [3, 5, 8]])

In [66]:
from numpy import newaxis

In [68]:
a

array([1, 2, 3])

In [71]:
arr = np.array([
    [1, 2],
    [3, 4]
])

In [73]:
arr[:, newaxis] #create 2D array for input array

array([[[1, 2]],

       [[3, 4]]])

In [74]:
arr.ndim

2

In [75]:
a[:, newaxis]

array([[1],
       [2],
       [3]])

In [76]:
b[:, newaxis]

array([[3],
       [4],
       [5]])

In [77]:
np.column_stack((a[:, newaxis], b[:, newaxis]))

array([[1, 3],
       [2, 4],
       [3, 5]])

In [78]:
np.hstack((a[:, newaxis], b[:, newaxis]))

array([[1, 3],
       [2, 4],
       [3, 5]])

In [79]:
np.vstack((a[:, newaxis], b[:, newaxis]))

array([[1],
       [2],
       [3],
       [3],
       [4],
       [5]])

In [80]:
np.column_stack is np.vstack

False

In [81]:
np.column_stack is np.hstack

False

In [82]:
np.vstack is np.column_stack

False

In [83]:
np.row_stack is np.hstack

False

In [84]:
np.row_stack is np.vstack

True

In [85]:
np.hstack((a,b))

array([1, 2, 3, 3, 4, 5])

In [86]:
np.row_stack((a,b))

array([[1, 2, 3],
       [3, 4, 5]])

### Array splitting, copy and view

In [95]:
a = np.floor(10 * rg.random((2,12)))

In [96]:
a

array([[7., 5., 9., 6., 5., 0., 4., 2., 1., 5., 7., 2.],
       [7., 5., 1., 9., 4., 2., 8., 1., 7., 1., 3., 2.]])

In [98]:
np.hsplit(a,3)

[array([[7., 5., 9., 6.],
        [7., 5., 1., 9.]]),
 array([[5., 0., 4., 2.],
        [4., 2., 8., 1.]]),
 array([[1., 5., 7., 2.],
        [7., 1., 3., 2.]])]

In [99]:
a.ndim

2

In [102]:
b = np.hsplit(a,3)

In [106]:
b

[array([[7., 5., 9., 6.],
        [7., 5., 1., 9.]]),
 array([[5., 0., 4., 2.],
        [4., 2., 8., 1.]]),
 array([[1., 5., 7., 2.],
        [7., 1., 3., 2.]])]

In [108]:
np.hsplit(a,(3,4))

[array([[7., 5., 9.],
        [7., 5., 1.]]),
 array([[6.],
        [9.]]),
 array([[5., 0., 4., 2., 1., 5., 7., 2.],
        [4., 2., 8., 1., 7., 1., 3., 2.]])]

In [109]:
a

array([[7., 5., 9., 6., 5., 0., 4., 2., 1., 5., 7., 2.],
       [7., 5., 1., 9., 4., 2., 8., 1., 7., 1., 3., 2.]])

##  <font color='Green'> Copies and Views </font>

#### <font color='blue'>When operating and manipulating arrays, their data is sometimes copied into a new array and sometimes not. This is often a source of confusion for beginners.</font>

In [122]:
a = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])

In [123]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [124]:
b = a

In [125]:
b #no new array object b is created

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [126]:
b is a

True

In [129]:
c = a.view()
c # view of data displayed by c for data of a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [130]:
c is a

False

In [131]:
c.base is a

True

In [132]:
c.flags.owndata

False

In [136]:
c= c.reshape((2,6)) # a does not change

In [137]:
c

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [138]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [142]:
c[0,5] = 999 # a also changes on value setting

In [143]:
c

array([[  1,   2,   3,   4,   5, 999],
       [  7,   8,   9,  10,  11,  12]])

In [144]:
a

array([[  1,   2,   3,   4],
       [  5, 999,   7,   8],
       [  9,  10,  11,  12]])

### Deep Copy

In [149]:
dc = a.copy() #dc does not share anything with a rather has its own structure and data

In [150]:
dc

array([[  1,   2,   3,   4],
       [  5, 999,   7,   8],
       [  9,  10,  11,  12]])

In [151]:
dc is a

False

In [152]:
dc.base is a

False