### My Jupyter notebook

> **Help you get started with the the Notebooks.ai for Python Programming**

_Need help, pleae follow the reference guide_

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

**Interesting Fact of the day**

> _Jupyter is very easy and fast responsive_



In [57]:
str = "United States"
print(str)

name = input("Please enter the name? ")
print("Welcome {}".format(name))

United States


Please enter the name?  oo


Welcome oo


In [50]:
name = input("Please enter the name: ")
age = int(input("Please enter the age: "))
if age >= 18:
    print("{}, You are allowed to vote!".format(name))
else:
    print("Sorry, you are ineligible to vote. Please come back after {} years".format(18 - age))

Please enter the name:  Piyush
Please enter the age:  2


Sorry, you are ineligible to vote. Please come back after 16 years


In [86]:
a = [1,2,3,4,5]
b = [1,2,3,4,5]

c = []
for i in range(len(a)):
    c.append(a[i]*b[i]);
print(c)


# C code
# for (i=0; i < a.len(); i++):
#     c[i] = a[i]*b[i];
# print(c)

[1, 4, 9, 16, 25]


In [87]:
import numpy as np

a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [85]:
b = a*2
b

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [91]:
a.shape #3- axes and 5- elements

(3, 5)

In [98]:
a.ndim # total number of dimensions

2

In [99]:
a.itemsize #buffer size of array

4

In [97]:
a.size # number of elements in array

15

In [100]:
type(a)

numpy.ndarray

In [101]:
a.data

In [102]:
a.dtype

dtype('int32')

In [121]:
myarray = np.array([(1,2,4),(4,5,6)])
myarray

array([[1, 2, 4],
       [4, 5, 6]])

In [122]:
myarray.ndim

2

In [137]:
b = np.array([(1.1,2,3),(2.2,4.1,5)])
b

array([[1.1, 2. , 3. ],
       [2.2, 4.1, 5. ]])

In [134]:
b.ndim

2

In [141]:
c = np.array([[1,2],[3,4]], dtype =complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [142]:
c.ndim

2

In [154]:
x = np.zeros([3,4], dtype=np.int32)
x

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [158]:
y = np.ones([2,3], dtype = np.int32)
y

array([[1, 1, 1],
       [1, 1, 1]])

In [161]:
twosarray = np.twos([2,3], dtype=np.int32) # error as no twos np attribute

### Above is multidimensional array
> Two dimensions having 3 axes each having 4 elements in each sub array

In [163]:
np.ones([2,3,4], dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [171]:
np.empty((2,3), np.int32)

array([[  818477104,         514,           0],
       [          0,           1, -2147483648]])

In [176]:
# arrange function is to create an array within limits defined and jump factor.
# It ignores the upto value.
np.arange(10,40,5)

array([10, 15, 20, 25, 30, 35])

In [184]:
np.arange(1,3,0.2)

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8])

In [189]:
from numpy import pi
# linspace is used to argument the number of elements in the array that we want between start and end arguments
np.linspace(0,2,8)

array([0.        , 0.28571429, 0.57142857, 0.85714286, 1.14285714,
       1.42857143, 1.71428571, 2.        ])

In [196]:
np.linspace(1,4,4)

array([1., 2., 3., 4.])

In [204]:
pi
x = np.linspace(0, 0.2 * pi, 10)
f= np.sin(x)
f

array([0.        , 0.06975647, 0.1391731 , 0.20791169, 0.27563736,
       0.34202014, 0.40673664, 0.46947156, 0.52991926, 0.58778525])