In [2]:
# The following script creates a two-dimensional NumPy array with four rows
# and five columns. The array contains random integers between 1 and 10. The
# array is then printed on the console.

import numpy as np
int_random = np.random.randint(1,10,size =(4,5),dtype=int)
int_random

array([[3, 2, 2, 6, 8],
       [1, 4, 7, 8, 2],
       [5, 9, 4, 1, 4],
       [9, 1, 3, 3, 3]])

In [6]:
# Let’s now try to see the number of dimensions and shape of our NumPy
# array.

print(int_random.ndim)
print(int_random.shape)

2
(4, 5)


In [13]:
# To traverse through items in a two-dimensional NumPy array, you need two
# for each loops: one for each row and the other for each column in the row.
# Let’s first use one for loop to print items in our two-dimensional NumPy
# array.

my_array = np.array([10,20,30,40,50,60])
#print(my_array.ndim)

for i in my_array:
    print(i)   

10
20
30
40
50
60


In [24]:
# -----
# To traverse through all the items in the two-dimensional array, you can use
# the nested foreach loop, as follows:

int_random
for rows  in int_random:
    for column in rows:
        print(column)

3
2
2
6
8
1
4
7
8
2
5
9
4
1
4
9
1
3
3
3


In [31]:
# To add the items into a NumPy array, you can use the append() method from
# the NumPy module. First, you need to pass the original array and the item
# that you want to append to the array to the append() method. The append()
# method returns a new array that contains newly added items appended to the
# end of the original array. The following script adds a text item “Yellow”
# to an existing array with three items.

my_array = np.array(['Red', 'Orange', 'Yellow'])
print(my_array)
my_array_extended = np.append(my_array,'Black')
print('The new array of colors is: ' + str(my_array_extended))


['Red' 'Orange' 'Yellow']
The new array of colors is: ['Red' 'Orange' 'Yellow' 'Black']


In [35]:
# In addition to adding one item at a time, you can also append an array of
# items to an existing array. The method remains similar to appending a single
# item. You just have to pass the existing array and the new array to the
# append() method, which returns a concatenated array where items from the
# new array are appended at the end of the original array.
my_array = np.array(['Red', 'Orange', 'Yellow'])
print(my_array)
my_array_extended = np.append(my_array,['Black', 'White'])
print(my_array_extended)

['Red' 'Orange' 'Yellow']
['Red' 'Orange' 'Yellow' 'Black' 'White']


In [45]:
import os
from os import listdir
path = 'D:\Learning\Python Practise Sets'
arr = os.listdir(path)
arr1 = []
for file in arr:
    if file.endswith('.pdf'):
        arr1.append(file)
#print(arr1)
for i in arr1:
    print(i)

1643273896036.pdf
1643374718964.pdf
1643467773243.pdf
1643558681083.pdf
1643696729223.pdf
1643786615864.pdf
1643786778372.pdf
1643871064727.pdf
1643960096841.pdf
1644046702450.pdf
1644128845797.pdf
1644133499093.pdf
1644214963090.pdf
1644303025809.pdf
1644401210844.pdf
1644475934000.pdf
1644487748389.pdf
1644561478570.pdf
1644566132154.pdf
1644648600029.pdf
Two_pages_only_Python_3_cheat_sheet__1635964164.pdf


In [54]:
# To add items in a two-dimensional NumPy array, you have to specify
# whether you want to add the new item as a row or as a column. To do so, you
# can take the help of the axis attribute of the append method.
# Let’s first create a 3 x 3 array of all zeros.

zeros_array = np.zeros([3,3])
print(zeros_array)
print(zeros_array.ndim)
# To add a new row in the above 3 x 3 array, you need to pass the original array
# to the new array in the form of a row vector and the axis attribute to the
# append() method. To add a new array in the form of a row, you need to set 0
# as the value for the axis attribute. Here is an example script.
extended_zeros_array = np.append(zeros_array, [[1, 2, 3]], axis = 0)
print(extended_zeros_array)


#axis = 0 means action on rows; axis = 1 means action on column
# arr = np.array([[1, 2, 3]])
# print(arr.ndim)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
2
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [1. 2. 3.]]


In [64]:
# To append a new array as a column in the existing 2-D array, you need to set
# the value of the axis attribute to 1.

# arr = np.array([[1],[2],[3]])
# print(arr.ndim)
print('Zero Array 2D: ')
print(zeros_array)

ext_array1 = np.append(zeros_array, [[1],[2],[3]], axis =1)
print('Extended Array: ')
print(ext_array1)

Zero Array 2D: 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Extended Array: 
[[0. 0. 0. 1.]
 [0. 0. 0. 2.]
 [0. 0. 0. 3.]]


In [71]:
# To delete an item from an array, you may use the delete() method. You need
# to pass the existing array and the index of the item to be deleted to the
# delete() method. The following script deletes an item at index 1 (second item)
# from the my_array array.

color_array = np.array(['Black', 'Orange', 'WHite'])
print(color_array)

print('array after deletion: ')
updated_array = np.delete(color_array, 1)
print(updated_array)

['Black' 'Orange' 'WHite']
array after deletion: 
['Black' 'WHite']
